name = "portfolio-sv"
compatibility_date = "2024-04-03"
pages_build_output_dir = ".svelte-kit/cloudflare"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
binding = "STATIC_ASSETS"
directory = ".svelte-kit/cloudflare"
